export const NAVIGATE_ROUTE = 'NAVIGATE_ROUTE';

// US ALBUM
export const GET_TOP_5_ALBUM_US = 'GET_TOP_5_ALBUM_US';
export const GET_TOP_5_ALBUM_US_SUCCESS = 'GET_TOP_5_ALBUM_US_SUCCESS';
export const GET_TOP_5_ALBUM_US_FAIL = 'GET_TOP_5_ALBUM_US_FAIL';

// KOREA ALBUM
export const GET_TOP_5_ALBUM_KOREA = 'GET_TOP_5_ALBUM_KOREA';
export const GET_TOP_5_ALBUM_KOREA_SUCCESS = 'GET_TOP_5_ALBUM_KOREA_SUCCESS';
export const GET_TOP_5_ALBUM_KOREA_FAIL = 'GET_TOP_5_ALBUM_KOREA_FAIL';

// VIETNAM ALBUM
export const GET_TOP_5_ALBUM_VIETNAM = 'GET_TOP_5_ALBUM_VIETNAM';
export const GET_TOP_5_ALBUM_VIETNAM_SUCCESS =
    'GET_TOP_5_ALBUM_VIETNAM_SUCCESS';
export const GET_TOP_5_ALBUM_VIETNAM_FAIL = 'GET_TOP_5_ALBUM_VIETNAM_FAIL';

// NEW DAY ALBUM
export const GET_ALBUM_FOR_NEW_DAY = 'GET_ALBUM_FOR_NEW_DAY';
export const GET_ALBUM_FOR_NEW_DAY_SUCCESS = 'GET_ALBUM_FOR_NEW_DAY_SUCCESS';
export const GET_ALBUM_FOR_NEW_DAY_FAIL = 'GET_ALBUM_FOR_NEW_DAY_FAIL';

// US RAP ALBUM
export const GET_ALBUM_US_RAP_HIPHOP = 'GET_ALBUM_US_RAP_HIPHOP';
export const GET_ALBUM_US_RAP_HIPHOP_SUCCESS =
    'GET_ALBUM_US_RAP_HIPHOP_SUCCESS';
export const GET_ALBUM_US_RAP_HIPHOP_FAIL = 'GET_ALBUM_US_RAP_HIPHOP_FAIL';

// TOP SINGERS
export const GET_TOP_SINGERS = 'GET_TOP_SINGERS';
export const GET_TOP_SINGERS_SUCCESS = 'GET_TOP_SINGERS_SUCCESS';
export const GET_TOP_SINGERS_FAIL = 'GET_TOP_SINGERS_FAIL';

// TOP SINGLE US
export const GET_TOP_SINGLE_US = 'GET_TOP_SINGLE_US';
export const GET_TOP_SINGLE_US_SUCCESS = 'GET_TOP_SINGLE_US_SUCCESS';
export const GET_TOP_SINGLE_US_FAIL = 'GET_TOP_SINGLE_US_FAIL';

// PLAYER CONTROL
export const SELECT_SONG = 'SELECT_SONG';
export const LOOP_MODE = 'LOOP_MODE';
export const PLAY_STATUS = 'PLAY_STATUS';
export const SET_SONG_DURATION = 'SET_SONG_DURATION';
export const SET_SONG_CURRENT_POSITION = 'SET_SONG_CURRENT_POSITION';
