export const GET_TOP_5_ALBUM_US = 'GET_TOP_5_ALBUM_US';
export const GET_TOP_5_ALBUM_US_SUCCESS = 'GET_TOP_5_ALBUM_US_SUCCESS';
export const GET_TOP_5_ALBUM_US_FAIL = 'GET_TOP_5_ALBUM_US_FAIL';

export const GET_TOP_5_ALBUM_KOREA = 'GET_TOP_5_ALBUM_KOREA';
export const GET_TOP_5_ALBUM_KOREA_SUCCESS = 'GET_TOP_5_ALBUM_KOREA_SUCCESS';
export const GET_TOP_5_ALBUM_KOREA_FAIL = 'GET_TOP_5_ALBUM_KOREA_FAIL';

export const GET_TOP_5_ALBUM_VIETNAM = 'GET_TOP_5_ALBUM_VIETNAM';
export const GET_TOP_5_ALBUM_VIETNAM_SUCCESS =
    'GET_TOP_5_ALBUM_VIETNAM_SUCCESS';
export const GET_TOP_5_ALBUM_VIETNAM_FAIL = 'GET_TOP_5_ALBUM_VIETNAM_FAIL';
